### ISSUE TITLE
这个功能在 zhihu 无效，求教

### ISSUE THREAD

**Issue by Aiurvie** [zx69/request-retransmission-chrome-extensions#1]
我试了一下，这个在知乎上能够抓到 Post 的分析信息，但是抓不到请求的回答、评论信息。

很迷惑，请问博主你知道原理吗

**Comment by zx69** [comment]
能否贴一下具体的配置信息? 
我没抓取过zhihu的请求, 不清楚知乎具体的请求是哪些.

**Comment by Aiurvie** [comment]
![image](https://github.com/zx69/request-retransmission-chrome-extension/assets/10151921/1ebb0e83-a31d-42d3-a941-88d9672d2748)

没有什么额外的配置，就是单纯打开评论区，看看能不能抓到请求。
如图所示，知乎的 `/batch` 请求可以抓取的到，而红框内的都没有抓取到。

**Comment by zx69** [comment]
如果我没猜错, 这个配置项的[监听URL]你是不是配置了/batch请求的url?
![example-you163-1.png](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f04183c592f04a6eb7adeafb7956b81d~tplv-k3u1fbpfcp-watermark.image?)
这个插件的设计初衷是只拦截特定域名下的特定url的请求, 配置了这个[监听URL]项后, 只会对该URL其作用.
如果你需要对zhihu下全部请求进行拦截, 可以试试注释掉content_script.js里的44行~46行:
https://github.com/zx69/request-retransmission-chrome-extension/blob/1938b8436616f1cbae28ca0f81156fe3794188f2/content_script.js#L44

**Comment by Aiurvie** [comment]
不是哈，是我自己太弱智了。
也是太久没写 Javascript 了，我是参考你掘金的文章写的，搞了半天发现就改了个 `XHR` 而没有重写 `fetch`。
重写一下 `fetch`  就好

``` javascript
const originalFetch = window.fetch;

// 重写 fetch() 方法
window.fetch = function () {
    const args = Array.prototype.slice.call(arguments);
    console.log('发送请求：', args);

    return originalFetch.apply(this, args)
        .then(async function (response) {
            const url = response.url;
            const status = response.status;
            const data = await response.json();
            
            console.log(status, data, url);
            response.json = await function(){
                return data;
            }
            return response;
        })
        .catch(function (error) {
            console.error('请求失败：', error);
            throw error;
        });
};

```

**Comment by Aiurvie** [comment]
不是哈，是我自己太弱智了。
也是太久没写 Javascript 了，我是参考你掘金的文章写的，搞了半天发现就改了个 `XHR` 而没有重写 `fetch`。
重写一下 `fetch`  就好

``` javascript
const originalFetch = window.fetch;

// 重写 fetch() 方法
window.fetch = function () {
    const args = Array.prototype.slice.call(arguments);
    console.log('发送请求：', args);

    return originalFetch.apply(this, args)
        .then(async function (response) {
            const url = response.url;
            const status = response.status;
            const data = await response.json();
            
            console.log(status, data, url);
            response.json = await function(){
                return data;
            }
            return response;
        })
        .catch(function (error) {
            console.error('请求失败：', error);
            throw error;
        });
};

```
